### ISSUE TITLE
Upgrade to latest swagger version iff fixes multiform uploads

### ISSUE THREAD

**Issue by supamii** [supamii/ah-swagger-plugin#12]
A reminder

**Comment by sanmoy27** [comment]
In post call I have there is a field named field1 which is mandatory to be provided in the body,which is mentioned as inputs field1:{required: true} but in swagger this input field is going as query parameter

**Comment by sanmoy27** [comment]
In post call I have there is a field named field1 which is mandatory to be provided in the body,which is mentioned as inputs field1:{required: true} but in swagger this input field is going as query parameter.
When I am mentioning it in model schema it is going in body as well as quey parameters.
I want to mention only in body not as query parameters

**Comment by supamii** [comment]
Would you mind reposting a new comment/issue instead of this one?  I'd like to avoid causing any confusion

**Comment by sanmoy27** [comment]
In post call I have there is a field named field1 which is mandatory to be provided in the body,which is mentioned as inputs field1:{required: true} but in swagger this input field is going as query parameter.
When I am mentioning it in model schema it is going in body as well as quey parameters.
I want to mention only in body not as query parameters

**Comment by supamii** [comment]
multiform options have been resolved in #18

**Comment by sanmoy27** [comment]
Is it published in npm, I want to update the document in npm how can I do
that

On 14 Jan 2017 5:27 a.m., "Son-Huy Pham" <notifications@github.com> wrote:

multiform options have been resolved in #18
<https://github.com/supamii/ah-swagger-plugin/issues/18>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/supamii/ah-swagger-plugin/issues/12#issuecomment-272579876>,
or mute the thread
